# Generated by Django 5.2.4 on 2026-07-11 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HYPERTENSION', 'Hypertension'), ('DIABETES', 'Diabetes'), ('HEART_RATE', 'Heart rate'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='type')),
                ('niveau', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='level')),
                ('message', models.TextField(verbose_name='message')),
                ('source', models.CharField(choices=[('SYSTEM_RULE', 'System rule'), ('DOCTOR', 'Doctor'), ('MANUAL', 'Manual')], default='SYSTEM_RULE', max_length=20, verbose_name='source')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_alerts', to='profiles.patientprofile', verbose_name='patient profile')),
            ],
            options={
                'verbose_name': 'medical alert',
                'verbose_name_plural': 'medical alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='alerts_medi_patient_2ec256_idx')],
            },
        ),
    ]
