# Generated by Django 5.2.4 on 2026-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalalert',
            name='is_read',
        ),
        migrations.AddField(
            model_name='medicalalert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SEEN', 'Seen'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=10, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='medicalalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
