# Generated by Django 5.2.4 on 2026-07-10 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groupe_sanguin', models.CharField(choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='blood group')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('antecedents_familiaux', models.TextField(blank=True, verbose_name='family medical history')),
                ('maladies_chroniques', models.TextField(blank=True, verbose_name='chronic diseases')),
                ('traitements_actuels', models.TextField(blank=True, verbose_name='current treatments')),
                ('notes_medicales', models.TextField(blank=True, verbose_name='medical notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='profiles.patientprofile', verbose_name='patient profile')),
            ],
            options={
                'verbose_name': 'medical record',
                'verbose_name_plural': 'medical records',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('patient',), name='unique_medical_record_patient')],
            },
        ),
    ]
