# Generated by Django 5.2.4 on 2026-07-10 19:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='name')),
                ('gravite', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10, verbose_name='severity')),
                ('reaction', models.TextField(verbose_name='reaction')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies_set', to='medical_records.medicalrecord', verbose_name='medical record')),
            ],
            options={
                'verbose_name': 'allergy',
                'verbose_name_plural': 'allergies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_maladie', models.CharField(max_length=255, verbose_name='disease name')),
                ('date_diagnostic', models.DateField(blank=True, null=True, verbose_name='diagnosis date')),
                ('gravite', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10, verbose_name='severity')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CONTROLLED', 'Controlled')], default='ACTIVE', max_length=12, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='medical_records.medicalrecord', verbose_name='medical record')),
            ],
            options={
                'verbose_name': 'chronic disease',
                'verbose_name_plural': 'chronic diseases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='medical_records.medicalrecord', verbose_name='medical record')),
            ],
            options={
                'verbose_name': 'medical note',
                'verbose_name_plural': 'medical notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
