# Generated by Django 5.2.4 on 2026-07-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_allergy_chronicdisease_medicalnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='allergies',
            new_name='allergies_text',
        ),
        migrations.AlterField(
            model_name='allergy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='medical_records.medicalrecord', verbose_name='medical record'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='nom_maladie',
            field=models.CharField(db_index=True, max_length=255, verbose_name='disease name'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CONTROLLED', 'Controlled')], db_index=True, default='ACTIVE', max_length=12, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='medicalnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
