# Generated by Django 5.2.4 on 2026-07-11 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_rename_allergies_medicalrecord_allergies_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_medicament', models.CharField(max_length=255, verbose_name='medication name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('dosage', models.CharField(max_length=255, verbose_name='dosage')),
                ('frequence', models.CharField(max_length=255, verbose_name='frequency')),
                ('voie_administration', models.CharField(blank=True, max_length=255, verbose_name='administration route')),
                ('date_debut', models.DateField(verbose_name='start date')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical_records.medicalrecord', verbose_name='medical record')),
                ('prescrit_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to=settings.AUTH_USER_MODEL, verbose_name='prescribed by')),
            ],
            options={
                'verbose_name': 'treatment',
                'verbose_name_plural': 'treatments',
                'ordering': ['-created_at'],
            },
        ),
    ]
