# Generated by Django 5.2.4 on 2026-07-11 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_treatment'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField(verbose_name='consultation date')),
                ('motif', models.TextField(verbose_name='reason')),
                ('diagnostic', models.TextField(blank=True, verbose_name='diagnosis')),
                ('symptomes', models.TextField(blank=True, verbose_name='symptoms')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_medecin', to='profiles.doctorprofile', verbose_name='doctor profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='profiles.patientprofile', verbose_name='patient profile')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-date_consultation'],
                'indexes': [models.Index(fields=['patient', 'date_consultation'], name='medical_rec_patient_59dda0_idx')],
            },
        ),
    ]
