# Generated by Django 5.2.4 on 2026-07-11 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_consultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='title')),
                ('type_document', models.CharField(choices=[('ORDONNANCE', 'Ordonnance'), ('ANALYSE', 'Analyse'), ('RADIO', 'Radio'), ('COMPTE_RENDU', 'Compte rendu'), ('CERTIFICAT', 'Certificat'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='document type')),
                ('fichier', models.FileField(upload_to='medical_documents/', verbose_name='file')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_document', models.DateField(verbose_name='document date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_records.medicalrecord', verbose_name='medical record')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'medical document',
                'verbose_name_plural': 'medical documents',
                'ordering': ['-date_document'],
                'indexes': [models.Index(fields=['medical_record', 'date_document'], name='medical_rec_medical_a5c8b0_idx')],
            },
        ),
    ]
