# Generated by Django 5.2.4 on 2026-07-10 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGlucose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='value')),
                ('unite', models.CharField(choices=[('G_PER_L', 'g/L'), ('MG_PER_DL', 'mg/dL')], default='MG_PER_DL', max_length=10, verbose_name='unit')),
                ('type_mesure', models.CharField(choices=[('FASTING', 'Fasting'), ('POST_MEAL', 'Post meal'), ('RANDOM', 'Random')], default='FASTING', max_length=20, verbose_name='measurement type')),
                ('source_mesure', models.CharField(choices=[('MANUAL', 'Manual'), ('DEVICE', 'Device'), ('CONNECTED_DEVICE', 'Connected device')], default='MANUAL', max_length=20, verbose_name='measurement source')),
                ('commentaire', models.TextField(blank=True, verbose_name='comment')),
                ('date_mesure', models.DateTimeField(verbose_name='measurement date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_glucoses', to='profiles.patientprofile', verbose_name='patient profile')),
            ],
            options={
                'verbose_name': 'blood glucose',
                'verbose_name_plural': 'blood glucoses',
                'ordering': ['-date_mesure', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'date_mesure'], name='monitoring__patient_28000f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolique', models.PositiveIntegerField(verbose_name='systolic')),
                ('diastolique', models.PositiveIntegerField(verbose_name='diastolic')),
                ('frequence_cardiaque', models.PositiveIntegerField(blank=True, null=True, verbose_name='heart rate')),
                ('source_mesure', models.CharField(choices=[('MANUAL', 'Manual'), ('DEVICE', 'Device'), ('CONNECTED_DEVICE', 'Connected device')], default='MANUAL', max_length=20, verbose_name='measurement source')),
                ('measurement_context', models.CharField(choices=[('REST', 'Rest'), ('EXERCISE', 'Exercise'), ('STRESS', 'Stress'), ('ILLNESS', 'Illness')], default='REST', max_length=20, verbose_name='measurement context')),
                ('commentaire', models.TextField(blank=True, verbose_name='comment')),
                ('date_mesure', models.DateTimeField(verbose_name='measurement date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressures', to='profiles.patientprofile', verbose_name='patient profile')),
            ],
            options={
                'verbose_name': 'blood pressure',
                'verbose_name_plural': 'blood pressures',
                'ordering': ['-date_mesure', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'date_mesure'], name='monitoring__patient_10354f_idx')],
            },
        ),
    ]
