# Generated by Django 5.2.4 on 2026-07-10 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodglucose',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='bloodglucose',
            name='unite',
            field=models.CharField(choices=[('G_PER_L', 'g/L'), ('MG_PER_DL', 'mg/dL')], default='G_PER_L', max_length=10, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='bloodglucose',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000)], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolique',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)], verbose_name='diastolic'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='frequence_cardiaque',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)], verbose_name='heart rate'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolique',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(250)], verbose_name='systolic'),
        ),
    ]
