# Generated by Django 5.2.4 on 2026-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_bloodglucose_updated_at_bloodpressure_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='bras_utilise',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('BOTH', 'Both')], default='BOTH', max_length=10, verbose_name='arm used'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='numero_mesure',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='measurement number'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='position',
            field=models.CharField(choices=[('SITTING', 'Sitting'), ('STANDING', 'Standing'), ('LYING', 'Lying')], default='SITTING', max_length=10, verbose_name='position'),
        ),
    ]
