# Generated by Django 5.2.4 on 2026-07-13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_bloodpressure_bras_utilise_bloodpressure_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodglucose',
            name='contexte_repas',
            field=models.CharField(
                choices=[
                    ('BEFORE_MEAL', 'Before meal'),
                    ('AFTER_MEAL', 'After meal'),
                    ('NO_MEAL', 'No meal'),
                ],
                default='BEFORE_MEAL',
                max_length=20,
                verbose_name='meal context',
            ),
        ),
        migrations.AddField(
            model_name='bloodglucose',
            name='hba1c',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name='HbA1c',
            ),
        ),
        migrations.AddField(
            model_name='bloodglucose',
            name='heure_mesure',
            field=models.TimeField(blank=True, null=True, verbose_name='measurement time'),
        ),
        migrations.AddField(
            model_name='bloodglucose',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='bloodglucose',
            name='type_prelevement',
            field=models.CharField(
                choices=[
                    ('CAPILLARY', 'Capillary'),
                    ('LABORATORY', 'Laboratory'),
                    ('SENSOR', 'Sensor'),
                ],
                default='CAPILLARY',
                max_length=20,
                verbose_name='sample type',
            ),
        ),
    ]
