# Generated by Django 5.2.4 on 2026-07-13

from django.db import migrations


def copy_comments_to_notes(apps, schema_editor):
    """Preserve legacy comments in notes without overwriting existing notes."""
    BloodGlucose = apps.get_model('monitoring', 'BloodGlucose')

    for measurement in BloodGlucose.objects.filter(notes='').exclude(commentaire='').iterator():
        measurement.notes = measurement.commentaire
        measurement.save(update_fields=['notes'])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_bloodglucose_diabetes_follow_up'),
    ]

    operations = [
        migrations.RunPython(copy_comments_to_notes, migrations.RunPython.noop),
    ]
