# Generated by Django 5.2.4 on 2026-07-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_copy_bloodglucose_comments_to_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodglucose',
            name='commentaire',
        ),
    ]
