# Generated by Django 5.2.4 on 2026-07-16

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_remove_bloodglucose_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodglucose',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('25'))], verbose_name='HbA1c'),
        ),
        migrations.AlterField(
            model_name='bloodglucose',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1500'))], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolique',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='diastolic'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='frequence_cardiaque',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='heart rate'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolique',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)], verbose_name='systolic'),
        ),
    ]
