# Generated by Django 5.2.4 on 2026-07-10 19:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialite', models.CharField(max_length=255, verbose_name='specialty')),
                ('numero_ordre', models.CharField(max_length=100, unique=True, verbose_name='registration number')),
                ('hopital', models.CharField(max_length=255, verbose_name='hospital')),
                ('annees_experience', models.PositiveSmallIntegerField(verbose_name='years of experience')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'doctor profile',
                'verbose_name_plural': 'doctor profiles',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_doctor_profile_user')],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_naissance', models.DateField(verbose_name='date of birth')),
                ('sexe', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='sex')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight')),
                ('taille', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='height')),
                ('antecedents', models.TextField(blank=True, verbose_name='medical history')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'patient profile',
                'verbose_name_plural': 'patient profiles',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_patient_profile_user')],
            },
        ),
    ]
