# Generated by Django 5.2.4 on 2026-07-16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=10, verbose_name='status')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='assigned at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='profiles.doctorprofile', verbose_name='doctor profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='profiles.patientprofile', verbose_name='patient profile')),
            ],
            options={
                'verbose_name': 'patient-doctor assignment',
                'verbose_name_plural': 'patient-doctor assignments',
                'ordering': ['-assigned_at'],
                'indexes': [
                    models.Index(fields=['doctor', 'status'], name='prof_assign_doc_status_idx'),
                    models.Index(fields=['patient', 'status'], name='prof_assign_pat_status_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_assignment'),
                    models.CheckConstraint(condition=models.Q(ended_at__isnull=True, status='ACTIVE') | models.Q(ended_at__isnull=False, status='ENDED'), name='assignment_status_matches_end_date'),
                ],
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', through='profiles.PatientDoctorAssignment', to='profiles.patientprofile', verbose_name='patients'),
        ),
    ]
